on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Create google-services.json
        if: ${{ steps.release.outputs.release_created }}
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./composeApp/google-services.json
      - name: Set up JDK
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Android App
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew :composeApp:assembleRelease
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk
      - name: Firebase App Distribution
        if: ${{ steps.release.outputs.release_created }}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          testers: "kevinah95@gmail.com"
          file: ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk
          releaseNotes: ${{ steps.release.outputs.body }}